@startuml
actor Оператор
participant MES
participant "Кэш" as cache
participant "База данных" as db

== Чтение списка заказов ==
Оператор -> MES: Запрос на получение списка заказов
MES -> cache: Проверка наличия данных
alt Данные есть в cacheе
    cache -> MES: Получение данных из кэша
    MES -> Оператор: Получение списка заказов
else Данных нет в кэше
    MES -> db: Запрос на получение списка заказов из БД
    db -> MES: Получение списка заказов
    MES -> cache: Сохранение данных в кэш
    MES -> Оператор: Получение списка заказов
end

== Изменение статуса заказа ==
Оператор -> MES: Запрос на изменение статуса заказа
MES -> db: Обновление статуса заказа
db -> MES: Подтверждение обновления
MES -> cache: Инвалидация данных о заказе
MES -> Оператор: Подтверждение изменения статуса
@enduml